# Run each test as it builds, writing output to both stdout and a log file
run = Builder(action = "$SOURCE | tee $TARGET")
env = Environment(BUILDERS = { "Run" : run })
env.Append(CFLAGS = ["-fprofile-arcs", "-ftest-coverage"])
env.Append(LIBS = ["gcov"])

# One c file per test
for f in Glob("*.c"):
    name = f.name.split(".")[0]
    env.Program(name, [ f, "lib/test.c", Glob("../src/*.c") ])
    env.Clean(name, name + ".gcno")
    env.Clean(name, name + ".gcda")
    env.Run(name + ".log", [ name, "lib/test.c" ])
