run = Builder(action = "$SOURCE | tee $TARGET")
gcov = Builder(action = "gcov -b $SOURCE | tee $TARGET")
env = Environment(BUILDERS = { "Run" : run, "Gcov" : gcov })
env.Append(CFLAGS = ["-fprofile-arcs", "-ftest-coverage"])
env.Append(LIBS = ["gcov"])

# Define all of our sources
files = Glob("*.c")
files.extend(Glob("lib/*.c"))
files.extend(Glob("src/*.c"))
env.Program("test", files);
env.Run("test.log", [ "test" ])

# Report code coverage
for f in Glob("src/*.c"):
    env.Gcov(f.name + ".coverage", f.name)
    env.Depends(f.name + ".coverage", "test.log")

# Cleanup gcov files
for f in files:
    name = str(f).split(".")[0]
    env.Clean("test.log", [name + ".gcda", name + ".gcno"])

# Cleanup coverage reports
for f in Glob("src/*.c"):
    env.Clean("test.log", "../" + f.name + ".gcov")

